package Pacote;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.LinkedList;
import java.util.Queue;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alex
 */
public class InterfaceGrafica extends javax.swing.JFrame {

    ArrayList<Atleta> listaGeral = new ArrayList<>();
    Deque<Atleta> mulheres = new ArrayDeque<>();
    Queue<Atleta> homens = new LinkedList<>();
    
    /**
     * Creates new form InterfaceGrafica
     */
    public InterfaceGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnAutores = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnMediaGeral = new javax.swing.JButton();
        btnMulherMaiorAltura = new javax.swing.JButton();
        btnMediaMasculinaBrasileira = new javax.swing.JButton();
        btnMostrarPilha = new javax.swing.JButton();
        btnMostrarFila = new javax.swing.JButton();
        btnRetirarPilha = new javax.swing.JButton();
        btnRetirarFila = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaTexto = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Masculino = new javax.swing.JRadioButton();
        Feminino = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        inputPais = new javax.swing.JTextField();
        inputAltura = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Campeonato2023");

        btnAutores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAutores.setText("Autores");
        btnAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoresActionPerformed(evt);
            }
        });

        btnCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnListar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnListar.setText("Listar Atletas");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnMediaGeral.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMediaGeral.setText("Média Geral");
        btnMediaGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaGeralActionPerformed(evt);
            }
        });

        btnMulherMaiorAltura.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMulherMaiorAltura.setText("Mulher Maior Altura");
        btnMulherMaiorAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulherMaiorAlturaActionPerformed(evt);
            }
        });

        btnMediaMasculinaBrasileira.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMediaMasculinaBrasileira.setText("Média Masculina Brasileira");
        btnMediaMasculinaBrasileira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaMasculinaBrasileiraActionPerformed(evt);
            }
        });

        btnMostrarPilha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMostrarPilha.setText("Mostrar Pilha");
        btnMostrarPilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarPilhaActionPerformed(evt);
            }
        });

        btnMostrarFila.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMostrarFila.setText("Mostrar Fila");
        btnMostrarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarFilaActionPerformed(evt);
            }
        });

        btnRetirarPilha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRetirarPilha.setText("Retirar da Pilha");
        btnRetirarPilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarPilhaActionPerformed(evt);
            }
        });

        btnRetirarFila.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRetirarFila.setText("Retirar da Fila");
        btnRetirarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarFilaActionPerformed(evt);
            }
        });

        AreaTexto.setEditable(false);
        AreaTexto.setColumns(20);
        AreaTexto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AreaTexto.setForeground(new java.awt.Color(0, 0, 0));
        AreaTexto.setRows(5);
        AreaTexto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        AreaTexto.setEnabled(false);
        jScrollPane1.setViewportView(AreaTexto);

        jLabel1.setText("Nome:");

        jLabel2.setText("País:");

        jLabel3.setText("Sexo:");

        buttonGroup1.add(Masculino);
        Masculino.setText("Masculino");

        buttonGroup1.add(Feminino);
        Feminino.setText("Feminino");

        jLabel4.setText("Altura:");

        inputNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        inputPais.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPaisActionPerformed(evt);
            }
        });

        inputAltura.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Feminino)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputNome)
                            .addComponent(inputPais, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)))
                    .addComponent(Masculino)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAutores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMostrarPilha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(btnMostrarFila))
                            .addComponent(btnMediaGeral))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRetirarPilha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMulherMaiorAltura))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMediaMasculinaBrasileira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRetirarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Masculino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Feminino)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnListar)
                    .addComponent(btnMediaGeral)
                    .addComponent(btnMulherMaiorAltura)
                    .addComponent(btnMediaMasculinaBrasileira))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAutores)
                    .addComponent(btnMostrarPilha)
                    .addComponent(btnMostrarFila)
                    .addComponent(btnRetirarPilha)
                    .addComponent(btnRetirarFila))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoresActionPerformed
        Autores au = new Autores();
        this.dispose();
        au.setVisible(true);
    }//GEN-LAST:event_btnAutoresActionPerformed

    private void btnMostrarPilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPilhaActionPerformed
        AreaTexto.setText("");
        if (mulheres.isEmpty()) {
            AreaTexto.setText("Pilha encontra-se vazia!");
            return;
        }
        for(Atleta a : mulheres) {
            AreaTexto.append("Nome: " + a.getNome() + ", País: " + a.getPais() + ", Sexo: " + a.getSexo() + ", Altura: " + a.getAltura() + "m\n");
        }
    }//GEN-LAST:event_btnMostrarPilhaActionPerformed

    private void inputPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPaisActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        AreaTexto.setText("");
        String nome = inputNome.getText();
        String pais = inputPais.getText();
        String sexo;
        if (Masculino.isSelected()) {
            sexo = "Masculino";
        } else {
            sexo = "Feminino";
        }
        String altura = inputAltura.getText();
        if (nome.isEmpty() || pais.isEmpty() || sexo.isEmpty() || altura.isEmpty()) {
            AreaTexto.setText("Algum campo está vazio!");
            return;
        }
        double alturaConvertida = Double.parseDouble(altura);
        if (sexo.equalsIgnoreCase("Feminino")) {
            mulheres.add(new Atleta(nome, pais, sexo, alturaConvertida));
        } else if (sexo.equalsIgnoreCase("Masculino")) {
            homens.add(new Atleta(nome, pais, sexo, alturaConvertida));
        }
        listaGeral.add(new Atleta(nome, pais, sexo, alturaConvertida));
        AreaTexto.setText("Atleta Cadastrado");
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        AreaTexto.setText("");
        if (listaGeral.isEmpty()) {
            AreaTexto.setText("Lista encontra-se vazia!");
            return;
        }
        for(Atleta a : listaGeral) {
            AreaTexto.append("Nome: " + a.getNome() + ", País: " + a.getPais() + ", Sexo: " + a.getSexo() + ", Altura: " + a.getAltura() + "m\n");
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnMostrarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarFilaActionPerformed
        AreaTexto.setText("");
        if (homens.isEmpty()) {
            AreaTexto.setText("Fila encontra-se vazia!");
            return;
        }
        for(Atleta a : homens) {
            AreaTexto.append("Nome: " + a.getNome() + ", País: " + a.getPais() + ", Sexo: " + a.getSexo() + ", Altura: " + a.getAltura() + "m\n");
        }
    }//GEN-LAST:event_btnMostrarFilaActionPerformed

    private void btnRetirarPilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarPilhaActionPerformed
        AreaTexto.setText("");
        if (mulheres.isEmpty()) {
            AreaTexto.setText("Pilha encontra-se vazia!");
            return;
        }
        AreaTexto.setText("Atleta Removida!");
        mulheres.pop();
    }//GEN-LAST:event_btnRetirarPilhaActionPerformed

    private void btnRetirarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarFilaActionPerformed
        AreaTexto.setText("");
        if (homens.isEmpty()) {
            AreaTexto.setText("Fila encontra-se vazia!");
            return;
        }
        AreaTexto.setText("Atleta Removido!");
        homens.remove();
    }//GEN-LAST:event_btnRetirarFilaActionPerformed

    private void btnMulherMaiorAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulherMaiorAlturaActionPerformed
        AreaTexto.setText("");
        if (mulheres.isEmpty()) {
            AreaTexto.setText("Pilha encontra-se vazia!");
            return;
        }
        String info = "";
        double maxAltura = Double.MIN_VALUE;
        for(Atleta a : mulheres) {
            double altura = a.getAltura();
            if (altura > maxAltura) {
                maxAltura = altura;
                info = "Nome: " + a.getNome() + ", País: " + a.getPais() + ", Sexo: " + a.getSexo() + ", Altura: " + a.getAltura() + "m\n";
            }
        }
        AreaTexto.setText("A atleta que obteve a maior altura na competição salto em altura: \n" + info);
    }//GEN-LAST:event_btnMulherMaiorAlturaActionPerformed

    private void btnMediaGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaGeralActionPerformed
        AreaTexto.setText("");
        if (listaGeral.isEmpty()) {
            AreaTexto.setText("Lista encontra-se vazia!");
            return;
        }
        int aux = 0;
        double acumulador = 0, mediaGeral = 0;
        for(Atleta a : listaGeral) {
            acumulador += a.getAltura();
            aux++;
        }
        mediaGeral = acumulador / aux;
        AreaTexto.setText("Média geral obtida na competição foi de: " + mediaGeral + "m");
    }//GEN-LAST:event_btnMediaGeralActionPerformed

    private void btnMediaMasculinaBrasileiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaMasculinaBrasileiraActionPerformed
        AreaTexto.setText("");
        if (homens.isEmpty()) {
            AreaTexto.setText("Fila encontra-se vazia!");
            return;
        }
        int aux = 0;
        double mediaBrasileiros = 0, acumulador = 0;
        for(Atleta a : homens) {
            if (a.getSexo().equalsIgnoreCase("Masculino") && a.getPais().equalsIgnoreCase("Brasil")) {
                acumulador += a.getAltura();
                aux++;
            }
        }
        
        if (aux == 0) {
            AreaTexto.setText("Nenhum brasileiro foi encontrado!");
            return;
        }
        
        mediaBrasileiros = acumulador / aux;
        AreaTexto.setText("A média obtida pelos atletas brasileiros foi de: " + mediaBrasileiros + "m");
    }//GEN-LAST:event_btnMediaMasculinaBrasileiraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaTexto;
    private javax.swing.JRadioButton Feminino;
    private javax.swing.JRadioButton Masculino;
    private javax.swing.JButton btnAutores;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnMediaGeral;
    private javax.swing.JButton btnMediaMasculinaBrasileira;
    private javax.swing.JButton btnMostrarFila;
    private javax.swing.JButton btnMostrarPilha;
    private javax.swing.JButton btnMulherMaiorAltura;
    private javax.swing.JButton btnRetirarFila;
    private javax.swing.JButton btnRetirarPilha;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField inputAltura;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputPais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
